[project]
name = "my-scrobbler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pylast>=7.0.2",
    "pyobjc-framework-cocoa>=12.1",
    "python-dotenv>=1.2.2",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.20.0",
]
