name: Build and Release my_scrobbler

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-release:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26.3"
          cache: true

      - name: Compile for macOS
        run: |
          # Compile for Apple Silicon
          GOOS=darwin GOARCH=arm64 go build -o build/my_scrobbler ./cmd/scrobbler

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/my_scrobbler
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Calculate Binary SHA-256
        id: calc_hash
        run: |
          HASH=$(shasum -a 256 build/my_scrobbler | awk '{print $1}')
          echo "sha256=$HASH" >> $GITHUB_OUTPUT

      - name: Checkout Homebrew Tap Repo
        uses: actions/checkout@v4
        with:
          repository: "mishazawa/homebrew-mishazawa"
          token: ${{ secrets.TAP_GITHUB_TOKEN }}
          path: "homebrew-mishazawa"

      - name: Update Formula File
        env:
          RELEASE_URL: ${{ steps.create_release.outputs.url }}
          RELEASE_SHA: ${{ steps.calc_hash.outputs.sha256 }}
          BINARY_NAME: "my_scrobbler"
        run: |
          FORMULA_PATH="homebrew-mishazawa/Formula/my-scrobbler.rb"
          ASSET_URL=$(echo "${{ env.RELEASE_URL }}" | sed 's/\/tag\//\/download\//')/$BINARY_NAME
          echo "Constructed URL: $ASSET_URL"

          sed -i '' "s,url \".*\",url \"$ASSET_URL\"," $FORMULA_PATH
          sed -i '' "s,sha256 \".*\",sha256 \"${{ env.RELEASE_SHA }}\"," $FORMULA_PATH

      - name: Create Pull Request in Tap Repo
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.TAP_GITHUB_TOKEN }}
          path: "homebrew-mishazawa"
          commit-message: "Update my_scrobbler to ${{ github.ref_name }}"
          title: "Update my_scrobbler to ${{ github.ref_name }}"
          body: |
            Automated formula update for `my_scrobbler` release [${{ github.ref_name }}](${{ steps.create_release.outputs.url }}).
          branch: "update-my_scrobbler-${{ github.ref_name }}"
          delete-branch: true
          base: main
          add-paths: |
            Formula/my-scrobbler.rb
