name: Build and Release my_scrobbler

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-release:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: "1.81.0"
          targets: aarch64-apple-darwin

      - name: Cache cargo registry and target
        uses: Swatinem/rust-cache@v2

      - name: Compile for macOS (Apple Silicon)
        run: |
          cargo build --release --target aarch64-apple-darwin
          mkdir -p build
          cp target/aarch64-apple-darwin/release/my_scrobbler build/my_scrobbler

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/my_scrobbler
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Calculate Binary SHA-256
        id: calc_hash
        run: |
          HASH=$(shasum -a 256 build/my_scrobbler | awk '{print $1}')
          echo "sha256=$HASH" >> $GITHUB_OUTPUT

      - name: Checkout Homebrew Tap Repo
        uses: actions/checkout@v4
        with:
          repository: "mishazawa/homebrew-mishazawa"
          token: ${{ secrets.TAP_GITHUB_TOKEN }}
          path: "homebrew-mishazawa"

      - name: Update Formula File
        env:
          RELEASE_SHA: ${{ steps.calc_hash.outputs.sha256 }}
        run: |
          FORMULA_PATH="homebrew-mishazawa/Formula/my-scrobbler.rb"

          TAG_NAME="${{ github.ref_name }}"
          VERSION_NUM="${TAG_NAME#v}"

          echo "Target Version: $VERSION_NUM"

          ASSET_URL="https://github.com/mishazawa/my_scrobbler/releases/download/${{ github.ref_name }}/my_scrobbler"
          echo "Constructed URL: $ASSET_URL"

          sed "s,url \".*\",url \"$ASSET_URL\"," $FORMULA_PATH | \
          sed "s,sha256 \".*\",sha256 \"$RELEASE_SHA\"," | \
          sed "s,version \".*\",version \"$VERSION_NUM\"," > temp_formula.rb

          mv temp_formula.rb $FORMULA_PATH

      - name: Create Pull Request in Tap Repo
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.TAP_GITHUB_TOKEN }}
          path: "homebrew-mishazawa"
          commit-message: "Update my_scrobbler to ${{ github.ref_name }}"
          title: "Update my_scrobbler to ${{ github.ref_name }}"
          body: |
            Automated formula update for `my_scrobbler` release [${{ github.ref_name }}](${{ steps.create_release.outputs.url }}).
          branch: "update-my_scrobbler-${{ github.ref_name }}"
          delete-branch: true
          base: main
          add-paths: |
            Formula/my-scrobbler.rb
